apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: foodtruck
data:
  NODE_ENV: "production"
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/foodtruck?schema=public"
